var MODS_DATA = [
  {
    "img": "images/Killfeed.png",
    "name": {
      "en": "MF KillFeed",
      "ru": "MF Килфид"
    },
    "shortDesc": {
      "en": "Comprehensive kill tracking system with weapon icons, leaderboard and Discord webhook integration for full server control.",
      "ru": "Полноценная система отслеживания убийств с иконками оружия, лидербордом и интеграцией Discord вебхуков."
    },
    "desc": {
      "en": "📖 A comprehensive kill tracking and statistics system for DAYZ.\nThis mod adds an informative killfeed with beautiful weapon icons,\na leaderboard system, and Discord webhook integration for complete\ncontrol over what happens on your server!\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n✨ MAIN FEATURES:\n\n🔫 KILLFEED SYSTEM:\n• Beautiful weapon icons (10 types)\n  - MELEE (melee weapons)\n  - PISTOL (pistols)\n  - RIFLE (assault rifles)\n  - SNIPER (sniper rifles)\n  - SHOTGUN (shotguns)\n  - EXPLOSIVE (explosives/grenades)\n  - VEHICLE (vehicles)\n  - ZOMBIE (zombies)\n  - ANIMAL (animals)\n  - SUICIDE (suicides)\n\n📊 KILLFEED INFORMATION:\n📏 Distance to target (in meters)\n🔫 Weapon type used\n💥 Damage dealt\n🎯 Headshot information\n👤 Killer and victim nicknames\n\n🏆 LEADERBOARD SYSTEM:\n• Top players by KD ratio (Kill/Death)\n• Automatic statistics tracking\n• Kill and death counter\n• Real-time updates\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n🔗 DISCORD WEBHOOK INTEGRATION:\n\n💀 KILL WEBHOOK:\nSends information about every kill on the server:\n- Who killed whom\n- What weapon was used\n- Distance\n- Damage\n- Was it a headshot\n\n💔 DAMAGE WEBHOOK:\nDamage tracking:\n- Who dealt damage\n- To whom\n- How much damage\n- Weapon type\n\n👑 ADMIN WEBHOOK:\nAdministrative actions:\n- Positions/Dmg/Type\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n⚙️ SETTINGS (CONFIG.JSON):\n\n📋 Available parameters:\n• VERSION - config version\n• needShowDistance - show distance (0/1)\n• needShowWeapon - show weapon (0/1)\n• needShowWeaponIcon - show icons (0/1)\n• needShowDamage - show damage (0/1)\n• enableKDLeaderboard - enable leaderboard (0/1)\n• canWorkWithAi - AI support (0/1)\n• canSendHeadshotInfo - headshot info (0/1)\n• killWebhookUrl - kill webhook URL\n• damageWebhookUrl - damage webhook URL\n• adminWebhookUrl - admin webhook URL\n\n💡 All settings can be customized for your server!\n\nMod client side are opened, you can change design and brand look for your server style",
      "ru": "📖 Полноценная система отслеживания убийств и статистики для DAYZ.\nМод добавляет информативный killfeed с красивыми иконками оружия,\nсистему лидерборда и интеграцию с Discord вебхуками для полного\nконтроля над происходящим на сервере!\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n✨ ОСНОВНЫЕ ВОЗМОЖНОСТИ:\n\n🔫 KILLFEED СИСТЕМА:\n• Красивые иконки оружия (10 типов)\n  - MELEE (холодное оружие)\n  - PISTOL (пистолеты)\n  - RIFLE (автоматы/штурмовые винтовки)\n  - SNIPER (снайперские винтовки)\n  - SHOTGUN (дробовики)\n  - EXPLOSIVE (взрывчатка/гранаты)\n  - VEHICLE (транспорт)\n  - ZOMBIE (зомби)\n  - ANIMAL (животные)\n  - SUICIDE (самоубийства)\n\n📊 ИНФОРМАЦИЯ В KILLFEED:\n📏 Расстояние до цели (в метрах)\n🔫 Тип использованного оружия\n💥 Нанесенный урон\n🎯 Информация о хедшотах (попадание в голову)\n👤 Никнеймы убийцы и жертвы\n\n🏆 СИСТЕМА ЛИДЕРБОРДА:\n• Топ игроков по соотношению KD (Kill/Death)\n• Автоматический подсчет статистики\n• Отслеживание убийств и смертей\n• Работает в реальном времени\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n🔗 DISCORD WEBHOOK ИНТЕГРАЦИЯ:\n\n💀 KILL WEBHOOK:\nОтправляет информацию о каждом убийстве на сервере:\n- Кто кого убил\n- Каким оружием\n- Дистанция\n- Урон\n- Был ли хедшот\n\n💔 DAMAGE WEBHOOK:\nОтслеживание нанесения урона:\n- Кто нанес урон\n- Кому\n- Сколько урона\n- Тип оружия\n\n👑 ADMIN WEBHOOK:\nАдминистративные действия:\n- Позиция выстрела\n- Позиция жертвы\n- Урон\n- Тип оружия\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n⚙️ НАСТРОЙКИ (CONFIG.JSON):\n\n📋 Доступные параметры:\n• VERSION - версия конфига\n• needShowDistance - показывать дистанцию (0/1)\n• needShowWeapon - показывать оружие (0/1)\n• needShowWeaponIcon - показывать иконки (0/1)\n• needShowDamage - показывать урон (0/1)\n• enableKDLeaderboard - включить лидерборд (0/1)\n• canWorkWithAi - работа с AI (0/1)\n• canSendHeadshotInfo - информация о хедшотах (0/1)\n• killWebhookUrl - ссылка на kill webhook\n• damageWebhookUrl - ссылка на damage webhook\n• adminWebhookUrl - ссылка на admin webhook\n\n💡 Все настройки можно изменить под свой сервер!\n\nКлиентская часть мода открыта, вы сами можете брендировать или изменить оформление под свой сервер"
    },
    "youtube": "",
    "discord": "https://discord.gg/6g8F3Ey37P"
  },
  {
    "img": "images/Mortar.png",
    "name": {
      "en": "Minethrower (Mortar in WOT style)",
      "ru": "MF Миномет (в стиле WOT)"
    },
    "shortDesc": {
      "en": "WOT-style tactical mortar that shifts your camera to a bird's-eye view for strategic fire control with HE, smoke and chemical shells.",
      "ru": "Тактический миномёт в стиле WOT — камера уходит в небо, управляйте огнём как в стратегии. ОФС, дымовые и химические снаряды."
    },
    "desc": {
      "en": "🪖 WOT-Style Mortar (Minethrower)\n\n«See everything. Strike anyone.»\n\nBring tactical artillery to your DayZ server!\nWhen deployed, the mortar lifts your camera into the sky — control fire like in a real-time strategy game.\nPick a target, aim to reduce spread… or fire instantly — but with reduced accuracy!\n\n💣 Ammunition Types:\n\n💥 High-Explosive (HE) — damage to players & vehicles\n🌫️ Smoke — concealment and tactical cover\n☣️ Chemical — area denial with status effects (optional)\n\n⚙️ Configuration (JSON + Client):\n\n📏 Shell flight radius & minimum firing distance\n🎯 Aim convergence/divergence speed — balance speed vs precision\n🔭 Camera zoom & viewing angle — customize your bird's-eye view\n\n👻 Dynamic object hiding:\n— Toggle visibility of players, cars, and moving entities\n— Flexible hide list by base classes (PlayerBase, CarScript, etc.)\n\n🛡️ SteamID64 Whitelist — only authorized players can use the mortar\n⚙️ Damage & fragmentation radius — configurable in client-side config.cpp\n\n«Artillery is when you don't see the enemy… but they're already dead.»",
      "ru": "🪖 Миномёт в стиле WOT\n\n«Видишь всё. Поражаешь любого.»\n\nДобавьте тактическую артиллерию в ваш DayZ-сервер!\nПри установке миномёта камера переносится в небо — вы управляете огнём как в стратегии.\nВыбирайте цель, сводите прицел для точности… или стреляйте сразу — но с разбросом!\n\n💣 Типы боеприпасов:\n\n💥 Осколочно-фугасные — урон по игрокам и технике\n🌫️ Дымовые — маскировка и тактическое прикрытие\n☣️ Химические — зона поражения с эффектами (по желанию)\n\n⚙️ Настройки (JSON + клиент):\n\n📏 Радиус полёта снарядов и минимальная дистанция выстрела\n🎯 Скорость сведения/разведения прицела — баланс между скоростью и точностью\n🔭 Зум и угол обзора камеры — настройте «вид с неба» под себя\n\n👻 Скрытие динамических объектов:\n— Вкл/выкл отображение игроков, машин и других движущихся целей\n— Гибкий лист скрытия по базовым классам (PlayerBase, CarScript и др.)\n\n🛡️ Whitelist по SteamID64 — только доверенные игроки могут использовать миномёт\n⚙️ Урон и радиус осколков — настраивается в config.cpp на клиенте\n\n«Артиллерия — это когда ты не видишь врага… но он уже мёртв.»"
    },
    "youtube": "",
    "discord": "https://discord.gg/6g8F3Ey37P"
  },
  {
    "img": "images/SpawnMenu.png",
    "name": {
      "en": "Stalker Anomaly Spawn Menu",
      "ru": "Меню спавна в стиле S.T.A.L.K.E.R. Anomaly"
    },
    "shortDesc": {
      "en": "S.T.A.L.K.E.R. Anomaly-inspired spawn menu with faction, location and character selection plus a full loadout economy system.",
      "ru": "Меню спавна в стиле S.T.A.L.K.E.R. Anomaly с выбором фракции, локации, персонажа и системой очков снаряжения."
    },
    "desc": {
      "en": "📦 S.T.A.L.K.E.R. Anomaly Style Spawn Menu\n\nDive into the Zone with a brand new spawn system! We've created a fully-featured spawn menu inspired by the Anomaly mod. Choose your faction, pick your drop location, and build your custom loadout based on equipment point costs. Select your character, faction, location, and head into the Zone. Or trust to random and make your experience unpredictable.\n\n🔥 Key Features:\n🎭 Faction Selection — full interface with icons and lore for each faction. Add any factions and custom lore\n🗺️ Location Picker — configurable spawn points for every faction with custom coordinates, VIP locations for special players\n👤 Character Selection — separate pools of male and female characters for each faction, exclusive characters for VIP players\n🎒 Loadout Economy — start with base points (default 1700). Spend them on weapons, mags, backpacks, and consumables right in the spawn menu\n💎 Advanced VIP System — VIP tiers grant different point amounts, access to different equipment tiers, different spawn points, and different characters. Configurable issuance until a specific date, by usage count, or unlimited\n\n🛠️ Additional Features:\n📖 Customizable player notifications about spawn location and faction\n⏰ Ability to set a delay before mod activation, allowing optimization with grave and insurance mods\n📋 Option to disable character selection\n🗺️ Option to disable spawn location selection\n💻 Configurable starting equipment points\n⏳ Configurable cooldowns for spawn points",
      "ru": "📦 Меню спавна в стиле S.T.A.L.K.E.R. Anomaly\n\nПогружайтесь в Зону с новой системой появления! Мы реализовали полноценное меню спавна, вдохновленное модом Anomaly. Выбирайте фракцию, локацию и собирайте уникальный пресет снаряжения, исходя из стоимости снаряжения в очках экипировки. Выбирайте персонажа, фракцию, локацию и вперед в Зону. Либо доверьтесь рандому и сделайте свой опыт непредсказуемым.\n\n🔥 Основной функционал:\n🎭 Выбор фракции — полноценный интерфейс с иконками и описанием каждой группировки. Можно добавить любые фракции и лор\n🗺️ Выбор локации — настраиваемые точки спавна для каждой фракции с возможностью задать координаты, VIP-точки для особых игроков\n👤 Выбор персонажа — раздельные пулы мужских и женских персонажей для каждой фракции, отдельные персонажи для VIP-игроков\n🎒 Экономика снаряжения — стартовый капитал (по умолчанию 1700 очков). Тратьте его на оружие, патроны, рюкзаки и расходники прямо в меню спавна\n💎 Продвинутая VIP-система — VIP-уровни дают разные очки, доступ к разным тирам снаряжения, к разным точкам спавна, к разным персонажам. Настройка выдачи до определенной даты, по количеству использований, либо безлимит\n\n🛠️ Дополнительный функционал:\n📖 Настройка уведомлений игроку о том, где и кем он появился\n⏰ Возможность задать паузу перед активацией мода, позволяет настроить так, чтобы оптимизировать работу вместе с модами на кресты и страховки\n📋 Возможность выключения выбора персонажа\n🗺️ Возможность отключения выбора позиции спавна игрока\n💻 Настройка стартовых очков снаряжения\n⏳ Настройка кулдауна для спавн-точек"
    },
    "youtube": "",
    "discord": "https://discord.gg/6g8F3Ey37P"
  }
];
